export const ROUTES = {
  home: 'index',
  books: 'books',
  bookId: 'books-id',
  dashboard: 'dashboard',
  favorites: 'favorites',
  pricing: 'pricing',
  checkout: 'pricing-checkout',
  signIn: 'sign-in',
  signInAdmin: 'admin-sign',
  signUp: 'sign-up',
  adminDashboard: 'admin-dashboard',
  adminBooks: 'admin-books',
  adminBooksNew: 'admin-books-new',
  adminCategories: 'admin-categories',
  adminReviews: 'admin-reviews',
  adminSettings: 'admin-settings',
  adminSubscriptions: 'admin-subscriptions',
  adminUsers: 'admin-users',
};
